packages:
  - apps/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - sharp
  - unrs-resolver

# Enable pnpm v10 monorepo-friendly deploy behavior
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
